dist: bionic

env:
  global:
    - CC_TEST_REPORTER_ID=895919e9413384a08a878a372ecad8e82ac0f6f80933e23cc36261e9986d27c0

language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"

before_install:
  - sudo apt-get update && sudo apt-get install -y gfortran libblas-dev liblapack-dev git build-essential cmake python3-dev
  - git clone https://github.com/LLNL/sundials.git
  - mkdir sundials/build && cd sundials/build && cmake -DLAPACK_ENABLE=ON ..
  - make && sudo make install
  - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
  - cd .. && cd ..

install:
  - echo $PYTHONPATH
  - pip3 install --upgrade numpy
  - python -m pip install -r requirements.txt
  - python -m pip install pytest coverage mock pytest-cov==2.6.1

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: pytest --runslow --cov=BondGraphTools --cov-report=xml test

after_script:
  ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
